[features]
seeds = false
skip-lint = false

[workspace]
members = [
  "programs/agent_mock_defi/programs/agent_mock_defi"
]

[programs.localnet]
agent_mock_defi = "XmnLz4Ez9CCJn6RnvGc6Z1J4sDdFqMjB2tZgkkA7sFP"

[programs.devnet]
agent_mock_defi = "XmnLz4Ez9CCJn6RnvGc6Z1J4sDdFqMjB2tZgkkA7sFP"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm ts-node programs/agent_mock_defi/tests/agent_mock_defi.ts"

