[features]
seeds = false
skip-lint = false

[programs.localnet]
agent_mock_defi = "AgntWal1et111111111111111111111111111111111"

[programs.devnet]
agent_mock_defi = "AgntWal1et111111111111111111111111111111111"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm ts-node programs/agent_mock_defi/tests/agent_mock_defi.ts"
